common:
  img_history_size: 50
  action_chunk_size: 1
  state_dim: 128

dataset:
  buffer_root: .tmp_amazon_light
  image_root: data/images
  history_len: 50
  max_samples: 200
  tokenizer_max_length: 64
  max_review_chars: 160
  max_text_history: 50
  min_history_len: 1
  ctrl_freq: 1
  text_branch_mask_prob: 0.1
  image_branch_mask_prob: 0.1

model:
  img_token_dim: 32
  state_token_dim: 128

  rdt:
    hidden_size: 1024
    depth: 2
    num_heads: 4

  noise_scheduler:
    num_train_timesteps: 100
    num_inference_timesteps: 10
    beta_schedule: linear
    prediction_type: sample
    clip_sample: false
